### ISSUE TITLE
Use of deprecated method from Scikit-Learn in Extractive Summarization feature

### ISSUE THREAD

**Issue by farisshamsur** [mesolitica/malaya#141]
In `malaya/model/extractive_summarization.py`, refer to line 112:

```python
features = self.vectorizer.get_feature_names() 

# get_feature_names() is deprecated for sklearn 1.2+
# should be changed to:

features = self.vectorizer.get_feature_names_out() 
```

[Scikit-learn's Count Vectorizer Documentation](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html#sklearn.feature_extraction.text.CountVectorizer)

**Comment by huseinzol05** [comment]
most of us still use 1.1.X, we should put condition version, if bigger 1.2, use `get_feature_names_out` else `get_feature_names`

**Comment by huseinzol05** [comment]
Latest master support >=1.2, https://github.com/mesolitica/malaya/blob/master/requirements.txt#L2
